WITH UNAVAILABLE AS (
    SELECT 
        H.CAR_ID CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE
        H.START_DATE <= '2022-10-16'
        AND
        H.END_DATE >= '2022-10-16'
)
SELECT DISTINCT
    H.CAR_ID CAR_ID,
    CASE
    WHEN U.CAR_ID IS NULL
    THEN '대여 가능'
    WHEN U.CAR_ID IS NOT NULL
    THEN '대여중'
    END
    AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H LEFT JOIN UNAVAILABLE U
    ON H.CAR_ID = U.CAR_ID
ORDER BY CAR_ID DESC
;
