SELECT
    T.YEAR YEAR,
    T.MONTH MONTH,
    T.GENDER GENDER,
    COUNT(DISTINCT T.USER_ID) USERS
FROM
    (
        SELECT
            DATE_FORMAT(S.SALES_DATE, '%Y') YEAR,
            DATE_FORMAT(S.SALES_DATE, '%m') MONTH,
            U.USER_ID USER_ID,
            U.GENDER GENDER
        FROM
            USER_INFO U INNER JOIN ONLINE_SALE S
            ON U.USER_ID=S.USER_ID
        WHERE U.GENDER IS NOT NULL
    )
    AS T
GROUP BY 
    T.YEAR, T.MONTH, T.GENDER
ORDER BY YEAR ASC, MONTH ASC, GENDER ASC
;
