SELECT
    F.CATEGORY,
    F.PRICE MAX_PRICE,
    F.PRODUCT_NAME
FROM
    (
    SELECT
        F.CATEGORY,
        F.PRICE,
        F.PRODUCT_NAME,
        RANK() OVER(PARTITION BY F.CATEGORY ORDER BY F.PRICE DESC) RANKING
    FROM
        FOOD_PRODUCT F
    WHERE F.CATEGORY IN ('과자', '국', '김치', '식용유')
    )
    F
WHERE 
    F.RANKING = 1
ORDER BY
    MAX_PRICE DESC
;
