SELECT
    R.FOOD_TYPE FOOD_TYPE,
    R.REST_ID REST_ID,
    R.REST_NAME REST_NAME,
    R.FAVORITES FAVORITES
FROM
    (SELECT
        R.REST_ID,
        R.REST_NAME,
        R.FOOD_TYPE,
        R.FAVORITES,
        RANK() OVER(PARTITION BY R.FOOD_TYPE ORDER BY R.FAVORITES DESC) RANKING
    FROM REST_INFO R)
    R
WHERE
    R.RANKING = 1
ORDER BY
    FOOD_TYPE DESC
;
