WITH MAX_FAVORITE_R AS (
    SELECT
        R.FOOD_TYPE FOOD_TYPE,
        MAX(R.FAVORITES) MAX_FAVORITES
    FROM
       REST_INFO R
    GROUP BY
        R.FOOD_TYPE
)
SELECT
    R.FOOD_TYPE FOOD_TYPE,
    R.REST_ID REST_ID,
    R.REST_NAME REST_NAME,
    R.FAVORITES FAVORITES
FROM
    REST_INFO R INNER JOIN MAX_FAVORITE_R M
    ON R.FOOD_TYPE=M.FOOD_TYPE
WHERE R.FAVORITES=M.MAX_FAVORITES
ORDER BY
    FOOD_TYPE DESC
;
