SELECT
    O.PRODUCT_ID PRODUCT_ID,
    P.PRODUCT_NAME PRODUCT_NAME,
    SUM(O.AMOUNT) * P.PRICE TOTAL_SALES
FROM
    FOOD_ORDER O INNER JOIN FOOD_PRODUCT P
    ON O.PRODUCT_ID = P.PRODUCT_ID
WHERE O.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY O.product_id, P.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC
;
