WITH
MEMBER_REVIEW AS (
    SELECT
        R.MEMBER_ID MEMBER_ID,
        P.MEMBER_NAME MEMBER_NAME,
        COUNT(*) CNT,
        RANK() OVER (ORDER BY COUNT(*) DESC) RNK
    FROM 
        REST_REVIEW R INNER JOIN MEMBER_PROFILE P
        ON R.MEMBER_ID=P.MEMBER_ID
    GROUP BY R.MEMBER_ID, P.MEMBER_NAME
)
SELECT
    M.MEMBER_NAME MEMBER_NAME,
    R.REVIEW_TEXT REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
FROM
    MEMBER_REVIEW M INNER JOIN REST_REVIEW R
    ON M.MEMBER_ID=R.MEMBER_ID
WHERE
    M.RNK=1
ORDER BY
    REVIEW_DATE ASC, REVIEW_TEXT ASC
;
