SELECT
    i.REST_ID REST_ID,
    i.REST_NAME REST_NAME,
    i.FOOD_TYPE FOOD_TYPE,
    i.FAVORITES FAVORITES,
    i.ADDRESS ADDRESS,
    ROUND(AVG(r.REVIEW_SCORE), 2) SCORE
FROM
    REST_INFO i INNER JOIN REST_REVIEW r ON i.REST_ID=r.REST_ID
WHERE
    i.ADDRESS like '서울%'
GROUP BY
    i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS
ORDER BY
    SCORE DESC, FAVORITES DESC
;
