SELECT
    b.BOOK_ID,
    DATE_FORMAT(b.PUBLISHED_DATE, '%Y-%m-%d') PUBLISHED_DATE
FROM
    BOOK b
WHERE
    YEAR(b.PUBLISHED_DATE) = 2021
    AND
    b.CATEGORY = '인문'
ORDER BY
    b.PUBLISHED_DATE ASC
;
