SELECT
    ord.FLAVOR FLAVOR
FROM
    FIRST_HALF ord INNER JOIN ICECREAM_INFO ice ON ord.FLAVOR=ice.FLAVOR
WHERE
    ord.TOTAL_ORDER > 3000
    AND
    ice.INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    ord.TOTAL_ORDER DESC
;
